<a href="https://colab.research.google.com/github/guebin/DL2026/blob/master/posts/01wk.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# 1. 강의영상

{{<video https://youtu.be/playlist?list=PLQqh36zP38-z5dhMMpc50GESsupd7NpaK&si=ARDd0I1nOWce0Hbj>}}

# 2. 코랩

`-` 코랩은 코드와 텍스트를 같이 볼 수 있는 형태로 이루어져 있음.

- 코드셀은 파이썬 명령어를 실행할 수 있고 코드의 결과를 확인할 수 있음.
- 텍스트셀은 글/수식/표/그림 등을 활용한 문서를 작성할 수 있음. (워드랑 같은 역할을 한다고 생각하면 된다.)

`-` 코랩은 코드+결과물을 출력하는 조각, 워드조각이 혼합이 되어서 나오는 형태임 --> 가독성이 뛰어나서 강의노트를 작성하기 적합함.

# 3. 필요한 지식

`-` 선형대수학

- 벡터와 행렬
- 행렬의 곱셈
- 트랜스포즈 (전치행렬)

`-` 기초통계학(확률의 개념 및 응용, 통계적추론)

- 정규분포, 이항분포
- 모수, 추정
- $X_i \overset{i.i.d.}{\sim} N(0,1)$

`-` 회귀분석

- 반응변수($y$), 설명변수($X$)
- ${\bf y}={\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬

- 파이썬기본문법
- 넘파이
- 전반적인 클래스 지식 (`__init__`, `self`, ...)
- 상속

# 4. 벡터와 행렬

`-` 레벨테스트 (2026년3월9일)

`-` 레벨테스트 결과 실력이 부족하다고 생각되면, 아래의 링크로 가서 보충수업을 들어보세요. (40분정도)

- <https://guebin.github.io/DL2026/posts/A2.html>

# 5. torch

> `torch`는 `numpy`처럼 파이썬에서 벡터/행렬연산을 쉽게 수행할 수 있도록 도와주는 툴이다.

In [7]:
import torch

## A. 1단계: `list` vs `torch.tensor`

`-` 선언

In [5]:
l = [1,2,3]
l

[1, 2, 3]

In [9]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

`-` 기본연산

In [12]:
a+a

tensor([2, 4, 6])

In [16]:
l+l

[1, 2, 3, 1, 2, 3]

In [19]:
3*a

tensor([3, 6, 9])

In [25]:
3*l

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [30]:
a+2

tensor([3, 4, 5])

In [31]:
l+2

TypeError: can only concatenate list (not "int") to list

> 벡터의 느낌이 나는것은 `[1,2,3]`이 아니라 `torch.tensor([1,2,3])` 임.

`-` 수학연산

In [32]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [34]:
torch.exp(a)

tensor([ 2.7183,  7.3891, 20.0855])

In [38]:
torch.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

In [39]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986])

## B. 2단계: 인덱싱

`-` 선언

In [46]:
l = [11, 22, 33, 44, 55, 66]
a = torch.tensor(l)

`-` 인덱스로 원소를 뽑아보자.

In [59]:
l[0],l[1],l[2],l[3],l[4],l[5]

(11, 22, 33, 44, 55, 66)

In [68]:
l[-1],l[-2],l[-3],l[-4],l[-5],l[-6]

(66, 55, 44, 33, 22, 11)

In [74]:
a[0],a[1],a[2],a[3],a[4],a[5]

(tensor(11), tensor(22), tensor(33), tensor(44), tensor(55), tensor(66))

In [75]:
a[-1],a[-2],a[-3],a[-4],a[-5],a[-6]

(tensor(66), tensor(55), tensor(44), tensor(33), tensor(22), tensor(11))

`-` `:`이용 (슬라이싱)

In [76]:
l[2:4]

[33, 44]

- 이런느낌임.. $2 \leq ... < 4$

In [96]:
a[2:4] # a[2]부터 a[4]까지인데, 끝점은 제외

tensor([33, 44])

In [95]:
l[2:] # l[2]부터 끝까지

[33, 44, 55, 66]

In [94]:
a[2:] # a[2]부터 끝까지

tensor([33, 44, 55, 66])

In [93]:
l[:4] # 처음부터 l[3]까지

[11, 22, 33, 44]

In [104]:
a[:4] # 처음부터 a[3]까지

tensor([11, 22, 33, 44])

In [110]:
l[:]

[11, 22, 33, 44, 55, 66]

In [111]:
a[:]

tensor([11, 22, 33, 44, 55, 66])

`-` 인덱스의 리스트로 원소를 뽑기

In [114]:
a[[1,3,4]]

tensor([22, 44, 55])

In [117]:
l[[1,3,4]]

TypeError: list indices must be integers or slices, not list

## C. 3단계: 2차원배열

`-` 중첩된 배열의 선언

In [188]:
l = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
a = torch.tensor(l)

In [189]:
l

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

In [190]:
a # 매트릭스처럼 보였지만, 사실 이것도 중첩된 배열임

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

`-` `l`의 원소를 인덱싱해보자.

In [146]:
l[0][0]

1

In [148]:
l[0][1]

2

In [156]:
l[1][2]

-3

In [151]:
l[-1][0]

-5

`-` `a`의 원소를 인덱싱해보자.

In [158]:
a

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

In [153]:
a[0][0]

tensor(1)

In [154]:
a[0][1]

tensor(2)

In [157]:
a[1][2]

tensor(-3)

In [155]:
a[-1][0]

tensor(-5)

`-` 새로운 기능 (`l`에서는 안되고 `a`에서만 가능함)

In [173]:
a[0,0]

tensor(1)

In [172]:
a[0,1]

tensor(2)

In [171]:
a[1,2]

tensor(-3)

In [170]:
a[-1,0]

tensor(-5)

`-` 응용

In [179]:
a

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

In [181]:
a[:,:]

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

In [182]:
a[:,[0,2]]

tensor([[ 1,  3],
        [-1, -3],
        [ 5,  7],
        [-5, -7]])

In [185]:
a[:2,[0,2,3]]

tensor([[ 1,  3,  4],
        [-1, -3, -4]])

> 정리: 1차원 배열을 의미하는 리스트를 텐서화하면, 그 결과는 거의 벡터처럼 취급해도 무방하다. 그리고 2차원 배열을 의미하는 (중첩된)리스트를 텐서화하면, 그 결과는 거의 행렬처럼 취급해도 무방하다.

## D. 4단계: `torch`를 이용한 행렬연산

`-` `torch`를 이용한 행렬곱

In [193]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [194]:
b = torch.tensor([[2,-1],[4,-3]])
b

tensor([[ 2, -1],
        [ 4, -3]])

In [195]:
a @ b

tensor([[ 10,  -7],
        [ 22, -15]])

`# 이상한 예제`

In [211]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[2,-1],[1/2,-3]])

In [208]:
a@b

RuntimeError: expected m1 and m2 to have the same dtype, but got: long int != float

해결책?

In [218]:
a = torch.tensor([[1.0 ,2.0],[3.0, 4.0]])
b = torch.tensor([[2.0,-1.0],[1/2,-3.0]])

In [219]:
a@b

tensor([[  3.,  -7.],
        [  8., -15.]])

`#`

`# 역행렬` -- 역행렬을 구하라..

In [222]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [224]:
torch.linalg.inv(a)

RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

해결책1

In [226]:
a = torch.tensor([[1.0,2.0],[3.0,4.0]])
a

tensor([[1., 2.],
        [3., 4.]])

In [229]:
torch.linalg.inv(a)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

해결책2

In [233]:
a = torch.tensor([[1.0,2],[3,4]])
a

tensor([[1., 2.],
        [3., 4.]])

In [234]:
torch.linalg.inv(a)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

해결책3

In [235]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [236]:
a.float()

tensor([[1., 2.],
        [3., 4.]])

In [242]:
torch.linalg.inv(a.float())

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

`#`

`# 연립1차방정식` -- 아래의 연립방정식을 풀어라.

$$\begin{cases}
w+2x+3y+4z = 1 \\
2w+2x+y = 9 \\
x-y=4 \\
3w+x-y+3z = 7
\end{cases}$$

행렬을 이용하여 위의식을 표현하면 아래와 같다.

$$\begin{bmatrix}
1 & 2 & 3 & 4 \\
2 & 2 & 1 & 0 \\
0 & 1 & -1 & 0 \\
3 & 1 & -1 & 3
\end{bmatrix}\begin{bmatrix}
w \\
x \\
y \\
z
\end{bmatrix} = \begin{bmatrix}
1 \\
9 \\
4 \\
7
\end{bmatrix}  $$

In [249]:
a = torch.tensor([[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]).float()
b = torch.tensor([[1],[9],[4],[7]]).float()

In [253]:
torch.linalg.inv(a) @ b

tensor([[ 2.0000],
        [ 3.0000],
        [-1.0000],
        [-1.0000]])

`#`