<a href="https://colab.research.google.com/github/guebin/DL2026/blob/master/posts/01wk.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# 1. 강의영상

# 2. 코랩

`-` 코랩은 코드와 텍스트를 같이 볼 수 있는 형태로 이루어져 있음. 

- 코드셀은 파이썬 명령어를 실행할 수 있고 코드의 결과를 확인할 수 있음. 
- 텍스트셀은 글/수식/표/그림 등을 활용한 문서를 작성할 수 있음. (워드랑 같은 역할을 한다고 생각하면 된다.) 

`-` 코랩은 코드+결과물을 출력하는 조각, 워드조각이 혼합이 되어서 나오는 형태임 --> 가독성이 뛰어나서 강의노트를 작성하기 적합함. 

# 3. 필요한 지식

`-` 선형대수학 

- 벡터와 행렬
- 행렬의 곱셈
- 트랜스포즈 (전치행렬) 

`-` 기초통계학(확률의 개념 및 응용, 통계적추론)

- 정규분포, 이항분포 
- 모수, 추정 
- $X_i \overset{i.i.d.}{\sim} N(0,1)$

`-` 회귀분석

- 반응변수($y$), 설명변수($X$)
- ${\bf y}={\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬 

- 파이썬기본문법
- 넘파이
- 전반적인 클래스 지식 (`__init__`, `self`, ...) 
- 상속 

# 4. 벡터와 행렬

`-` 레벨테스트 

`-` 레벨테스트 결과 실력이 부족하다고 생각한다면, 아래를 들어보세요. 

# 5. torch

In [2]:
import torch

## A. 1단계

`-` 선언 

In [14]:
a = torch.tensor([1,2,3])
l = [1,2,3]


`-` 기본연산

In [15]:
a+a

tensor([2, 4, 6])

In [16]:
l+l

[1, 2, 3, 1, 2, 3]

In [19]:
2*a

tensor([2, 4, 6])

In [20]:
2*l

[1, 2, 3, 1, 2, 3]

In [21]:
a+1

tensor([2, 3, 4])

In [22]:
l+1

TypeError: can only concatenate list (not "int") to list

`-` 수학연산 

In [112]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [113]:
torch.exp(a)

tensor([ 2.7183,  7.3891, 20.0855])

In [114]:
torch.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

In [115]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986])

## B. 2단계 

`-` 선언 

In [83]:
l = [11, 22, 33, 44, 55, 66]
a = torch.tensor(l)

`-` 인덱스로 접근

In [84]:
l[0], l[1], l[2], l[3], l[4], l[5], l[-1], l[-2]

(11, 22, 33, 44, 55, 66, 66, 55)

In [85]:
a[0], a[1], a[2], a[3], a[4], a[5], a[-1], a[-2]

(tensor(11),
 tensor(22),
 tensor(33),
 tensor(44),
 tensor(55),
 tensor(66),
 tensor(66),
 tensor(55))

`-` `:`이용 (슬라이싱)

In [45]:
l[2:4]

[33, 44]

In [46]:
a[2:4]

tensor([33, 44])

In [47]:
l[2:]

[33, 44, 55, 66]

In [48]:
a[2:]

tensor([33, 44, 55, 66])

In [52]:
l[:-2]

[11, 22, 33, 44]

In [53]:
a[:-2]

tensor([11, 22, 33, 44])

In [54]:
l[:]

[11, 22, 33, 44, 55, 66]

In [55]:
a[:]

tensor([11, 22, 33, 44, 55, 66])

`-` 인덱스의 리스트로 접근 

In [90]:
a[[0,2]]

tensor([11, 33])

In [91]:
l[[0,2]]

TypeError: list indices must be integers or slices, not list

## C. 3단계

`-` 중첩된 리스트의 선언

In [57]:
L = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A = torch.tensor(L)

In [59]:
L

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

In [60]:
A

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

`-` L의 원소 인덱싱

In [61]:
L[0][0]

1

In [63]:
L[0][1]

2

In [64]:
L[-1][0]

-5

`-` A의 원소 인덱싱 

In [66]:
A[0][0]

tensor(1)

In [67]:
A[1][2]

tensor(-3)

In [68]:
A[-1][0]

tensor(-5)

`-` A에서만 가능한 새로운 기능

In [69]:
A[0,0]

tensor(1)

In [70]:
A[1,2]

tensor(-3)

In [71]:
A[-1,0]

tensor(-5)

`-` 응용 (슬라이싱과 함께)

In [72]:
A

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

In [74]:
A[:,:]

tensor([[ 1,  2,  3,  4],
        [-1, -2, -3, -4],
        [ 5,  6,  7,  8],
        [-5, -6, -7, -8]])

In [93]:
A[:,[0,2]]

tensor([[ 1,  3],
        [-1, -3],
        [ 5,  7],
        [-5, -7]])

In [96]:
A[:2,[0,2,3]]

tensor([[ 1,  3,  4],
        [-1, -3, -4]])

> 정리: 리스트의 텐서화는 1차원배열(=벡터처럼 취급해도 무방)를 만들고 중첩된리스트의 텐서화는 2차원배열(=행렬처럼 취급해도 무방)을 만든다. 

## D. 4단계

`-` 행렬곱을 구하라. 

In [119]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[2,-1],[4,-3]])

In [121]:
A @ B

tensor([[ 10,  -7],
        [ 22, -15]])

`#  이상한예제`

In [135]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[2,-1],[1/2,-3]])

In [139]:
A@B

RuntimeError: expected m1 and m2 to have the same dtype, but got: long int != float

해결책? 

In [141]:
A = torch.tensor([[1.0,2.0],[3.0,4.0]])
B = torch.tensor([[2.0,-1.0],[1/2,-3.0]])

In [142]:
A@B

tensor([[  3.,  -7.],
        [  8., -15.]])

`#`

`# 역행렬` -- 역행렬을 구하라. 

In [123]:
A = torch.tensor([[1,2],[3,4]])
torch.linalg.inv(A)

RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

- ??

해결책1

In [128]:
A = torch.tensor([[1.0,2.0],[3.0,4.0]])
torch.linalg.inv(A)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [129]:
A @ torch.linalg.inv(A)

tensor([[1., 0.],
        [0., 1.]])

해결책2

In [130]:
A = torch.tensor([[1,2],[3,4]])
A

tensor([[1, 2],
        [3, 4]])

In [131]:
A.float()

tensor([[1., 2.],
        [3., 4.]])

In [134]:
torch.linalg.inv(A.float()) @ A.float()

tensor([[1., 0.],
        [0., 1.]])

`#`

`# 연립1차방정식` -- 아래의 연립방정식을 풀어라. 

$$
\begin{cases}
w + 2x + 3y + 4z = 1 \\
2w + 2x + y = 9 \\
x-y=4 \\ 
3w+x-y+3y = 7
\end{cases}
$$

매트릭스 형태로 위의 식을 표현하면 아래와 같다. 

$$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$$


In [145]:
A = torch.tensor([[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]).float()
A

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  2.,  1.,  0.],
        [ 0.,  1., -1.,  0.],
        [ 3.,  1., -1.,  3.]])

In [149]:
b = torch.tensor([[1],[9],[4],[7]]).float()
b

tensor([[1.],
        [9.],
        [4.],
        [7.]])

In [152]:
torch.linalg.inv(A) @ b

tensor([[ 2.0000],
        [ 3.0000],
        [-1.0000],
        [-1.0000]])

`#`

## E. 5단계

`-` 미묘한 차이 

In [97]:
A[0,:]

tensor([1, 2, 3, 4])

In [98]:
A[[0],:]

tensor([[1, 2, 3, 4]])

In [99]:
A[:,0]

tensor([ 1, -1,  5, -5])

In [100]:
A[:,[0]]

tensor([[ 1],
        [-1],
        [ 5],
        [-5]])

`-` 0차원, 1차원, 2차원... 

In [173]:
torch.tensor([[1,2,3],[1,2,3]]), torch.tensor([[1,2,3],[1,2,3]]).shape

(tensor([[1, 2, 3],
         [1, 2, 3]]),
 torch.Size([2, 3]))

In [172]:
torch.tensor([[1,2,3]]), torch.tensor([[1,2,3]]).shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [171]:
torch.tensor([[1],[2],[3]]), torch.tensor([[1],[2],[3]]).shape

(tensor([[1],
         [2],
         [3]]),
 torch.Size([3, 1]))

In [170]:
torch.tensor([1,2,3]), torch.tensor([1,2,3]).shape

(tensor([1, 2, 3]), torch.Size([3]))

In [169]:
torch.tensor([1]), torch.tensor([1]).shape

(tensor([1]), torch.Size([1]))

In [168]:
torch.tensor(1), torch.tensor(1).shape

(tensor(1), torch.Size([]))

`-` reshape

In [176]:
a = torch.tensor([1,2,3,4,5,6])
a

tensor([1, 2, 3, 4, 5, 6])

In [178]:
a.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [179]:
a.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [180]:
a.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`# reshape 고급`

In [181]:
a = torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

task1: [6,1]로 만들기

In [182]:
a.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [183]:
a.reshape(6,-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [184]:
a.reshape(-1,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

task2: [3,2]로 만들기

In [186]:
a.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [187]:
a.reshape(3,-1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [188]:
a.reshape(-1,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

task3: 6으로 만들기

In [193]:
a.reshape(6)

tensor([1, 2, 3, 4, 5, 6])

In [191]:
a.reshape(-1).shape

torch.Size([6])

`#`